spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  datasource:
    url: ${MYSQL_URL:''}
    username: ${MYSQL_USERNAME:''}
    password: ${MYSQL_PASSWORD:''}
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE



aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:''}
    accessKeyId: ${ALIYUN_OSS_ACCESS_KEY_ID:''}
    accessKeySecret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:''}
    bucketName: ${ALIYUN_OSS_BUCKET_NAME:''}

