spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  datasource:
    maximum-pool-size: 5
    max-lifetime: 300000
    connection-timeout: 30000
    initial-size: 1
    max-idle: 3
    min-idle: 1
    max-active: 5
    log-abandoned: true
    remove-abandoned: true
    remove-abandoned-timeout: 30000
    max-wait: 30000
    test-while-idle: true
    validation-query: select 1
    test-on-borrow: true
    min-evictable-idle-time-millis: 600000
    time-between-eviction-runs-millis: 300000
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
  boot:
    mariadb4j:
      databaseName: test